package:
  name: multivis
  version: 0.5.11

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - setuptools==68.2.2
    - pip==23.2.1
    - python==3.11.4
    - numpy==1.25.2
    - openpyxl=3.1.2
    - pandas==2.1.0
    - matplotlib==3.8.0
    - seaborn==0.12.2
    - networkx==3.1.0
    - statsmodels==0.14.0
    - scikits-bootstrap==1.1.0
    - scipy==1.11.2
    - scikit-learn==1.3.1
    - tqdm==4.66.1
    - xlrd==2.0.1

  run:
    - python==3.11.4
    - numpy==1.25.2
    - openpyxl=3.1.2
    - pandas==2.1.0
    - matplotlib==3.8.0
    - seaborn==0.12.2
    - networkx==3.1.0
    - statsmodels==0.14.0
    - scikits-bootstrap==1.1.0
    - scipy==1.11.2
    - scikit-learn==1.3.1
    - tqdm==4.66.1
    - xlrd==2.0.1

about:
  home: https://github.com/brettChapman
  license: MIT License
  summary: "Multivis is a data visualisation package that produces both static and interactive visualisations targeted towards the Omics community."

